### ISSUE TITLE
How to center the APOD

### ISSUE THREAD

**Issue by Rwolkenflitzer** [grenagit/MMM-APOD#3]
Hello,

How can I center the APOD?
By `position: "fullscreen_below"` it is put to the left side of the canvas.

**Comment by grenagit** [comment]
Hello,

If you want to place MMM-APOD in the center, you must use `position: "top_center"`. That’s what I use on my MagicMirror and it works very well!

From what I could read, `position: "fullscreen_below"` allows to position a module in the background on the whole screen.

**Comment by Rwolkenflitzer** [comment]
Hi,
Thanks for your reply!
I did so. Unfortunately it only works as long as the picture is narrow enough. Otherwise it covers the text of the side modules. A centered picture in the background would be perfect.

**Comment by grenagit** [comment]
@Rwolkenflitzer, I just pushed an update of the module **supporting APOD in the background**!

~~Can you test if the **testing branch** works what you want before I release the update for everyone?~~

*In your MagicMirror's :*
```shell
cd ~/MagicMirror/modules/MMM-APOD
git pull
```

Don’t forget to change the module position to "fullscreen_below" and restart your MagicMirror :wink:
